### ISSUE TITLE
Missing "end" results in copying the whole input data instead of error

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#126] opened 2022-02-03 12:58 UTC
https://github.com/TobiasNx/fix-FunctionalReview-Testing/blob/41e403a51e4a987192f27fd246c67c24725119b9/data/testing/missingErrorWhenTrailingEndIsMissing

instead of an error, a missing end results in passing through all input data.

Expected: error
Is: input-file

**Comment by blackwinter** [comment] 2022-02-03 13:06
Related to (or even duplicate of) #79?

**Comment by TobiasNx** [comment] 2022-02-03 14:16
Yes related and or duplicated, therefore we decided off board to close this and solve it  in #79

**Closed** 2022-02-03 14:17 UTC
Labels: duplicate
