### ISSUE TITLE
Add more Fix functions.

### ISSUE THREAD

**Issue by blackwinter** [metafacture/metafacture-fix#100] opened 2021-12-22 11:54 UTC
We're going to need some more Fix functions that aren't implemented yet. E.g.:

| Morph     | Fix           |
|-----------|---------------|
| `replace` | `replace_all` |
| `split`   | `split_field` |
| `unique`  | `uniq`        |

I'm just going to go ahead and implement those plus a bunch more from the [Catmandu Cheat Sheet](https://librecat.org/assets/catmandu_cheat_sheet.pdf).

Functional review: @TobiasNx
Code review: @fsteeg

**Comment by TobiasNx** [comment] 2021-12-22 13:57
In Catmandu `replace_all` does not seem to support regexp as in metafacture. That would be nice.

`unique` seem  to process only arrays in Catmandu. Metafacture is here also more powerful. 

`split_field` outputs arrays and differs from split-behavour in Metafacture.

Bonus: `Unique`/`uniq` objects not just strings would be awesome.

**Comment by blackwinter** [comment] 2021-12-22 15:05
> In Catmandu `replace_all` does not seem to support regexp as in metafacture. That would be nice.

What makes you think that? The cheat sheet says: `replace_all(title,'[au]','X')` -> `title: cXtmXndX`. And [the tests confirm](https://github.com/hbz/Catmandu/blob/dev/t/Catmandu-Fix-replace_all.t) this behaviour.

> `unique` seem to process only arrays in Catmandu. Metafacture is here also more powerful. [Bonus: `Unique`/`uniq` objects not just strings would be awesome.]

Well, yes, it seems that Metamorph's `unique` function is a little more powerful. But I don't think we've ever made use of that.

> `split_field` outputs arrays and differs from split-behavour in Metafacture.

Hm, other than the absence of arrays in Metamorph, I don't really see a difference. It just emits a repeated field instead of an actual array object.

But thanks for your input! Let's wait and see what our hybrid "better than both worlds" beast will look like in the end ;)

**Comment by blackwinter** [comment] 2022-01-13 09:59
@TobiasNx: Sorry, forgot to assign you for functional review.

**Comment by TobiasNx** [comment] 2022-01-14 14:11
This will take some time to review since this are a lot of functions

**Comment by blackwinter** [comment] 2022-01-14 14:48
That's understandable ;) Thanks for your diligence!

In effect, this means that #103 and #105 have passed code review, but won't be merged until both functional reviews are done - unless we decide otherwise.

**Comment by fsteeg** [comment] 2022-01-17 10:43
> In effect, this means that #103 and #105 have passed code review, but won't be merged until both functional reviews are done - unless we decide otherwise.

+1 for merging, we can always open issues/PRs for things that come up in reviews (cc @dr0i for #14).

**Comment by blackwinter** [comment] 2022-01-17 14:21
If nobody objects I'll merge #103 and #105 tomorrow.

**Comment by TobiasNx** [comment] 2022-01-18 09:11
I will use this post as list of tested functions:

One general question: "I've opted for the non-destructive approach w.r.t. `Values`" -> Is this the same as in Catmandu?

works:
`nothing`


@blackwinter have a look at these:

- [ ] `random`: seems generally to work but in the fix i have some questions: https://github.com/TobiasNx/fix-FunctionalReview-Testing/tree/master/data/review/random
- [ ]

**Comment by blackwinter** [comment] 2022-01-18 10:10
> `random`: Handling seems not to be "destructive" how is Catmandu operating this?

Existing value is replaced (see hbz/Catmandu@a3263b5; note that Catmandu doesn't have a concept of "marked arrays").

> `random`: This seems not to work. Do not know why. Not an index-number but $append is element name.

Seems to work (see 4850cbc). What did you expect instead?

**Comment by blackwinter** [comment] 2022-01-18 10:41
> `rename`: This only works on fields in an objects, not deeper nested structures.

Left as `TODO` in the [code](https://github.com/metafacture/metafacture-fix/pull/103/files#diff-dffdf77002e060149adb828b760328d625cd5cf1ba714c7020038049cc6090e4R199).

> `rename`: This seems not to work. Perhapse it is an array of objects.

Same as above.

> `rename`: Also you cannot rename all fields in root.

Path `.` not supported (yet).

See also hbz/Catmandu@544bb38 and 2acb29b.

**Comment by TobiasNx** [comment] 2022-01-18 10:45
> > `random`: This seems not to work. Do not know why. Not an index-number but $append is element name.
> 
> Seems to work (see [e77188b](https://github.com/metafacture/metafacture-fix/commit/e77188be3ec5314ffab5d47d7364141c84a8c0b7)). What did you expect instead?

```
  "animals" : {
    "$append" : "0"
  }
```
would have expected the same behaviour as with `others` that it would set "1" (the indexnumber) as fieldname instead of $append:

```
  "animals" : {
    "1" : "0"
  }
```

**Comment by blackwinter** [comment] 2022-01-18 10:50
> One general question: "I've opted for the non-destructive approach w.r.t. `Values`" -> Is this the same as in Catmandu?

I'm not sure, but it should be entirely implementation-dependent, no user-facing impact to be expected.

**Comment by blackwinter** [comment] 2022-01-18 11:12
> would have expected the same behaviour as with `others` that it would set "1" (the indexnumber) as fieldname instead of `$append`:

I see, that's our "array object" striking again :disappointed: (see fa0c10e)

I gotta admit, I'm _really_ not so sure at all that that's such a good idea...

**Comment by blackwinter** [comment] 2022-01-18 12:33
> `append`: Does not work with array and indexnumber

Kinda works, but order is changed (implementation first [removes element at index](https://github.com/metafacture/metafacture-fix/blob/fa0c10e3647dede451dedf2c77f95ffb9e8f2239/metafix/src/main/java/org/metafacture/metafix/Value.java#L873) and then [ignores index number](https://github.com/metafacture/metafacture-fix/blob/fa0c10e3647dede451dedf2c77f95ffb9e8f2239/metafix/src/main/java/org/metafacture/metafix/Value.java#L714) when adding transformed value).

> `append`: Does not work with all values of array of strings

Not sure what the cause is, offhand.

> `append`: Creates weird resutls. Should result in error

Turns array into string before appending.

See also hbz/Catmandu@3f6a304 and f19b34a.

**Comment by blackwinter** [comment] 2022-01-18 16:26
> `join_field`: seems to work

How? I don't see any expected values in the results.

> `join_field`: example of xml should response an error since it is not an array

Errors are generally avoided; unexpected values/types are either silently ignored or converted into strings. Shouldn't repeated (XML) values produce an array, though?

> `join_field`: it does not work with json-ararys

Indeed, same as `filter`.

See also a334312.

**Comment by blackwinter** [comment] 2022-01-18 16:45
> `replace_all`: works with simple strings and nested structures but has problems with (JSON?-)arrays

Same as `rename`.

See also af12b4f.

**Comment by blackwinter** [comment] 2022-01-19 11:38
Summary/next steps:

1. Array handling must be improved! (see #109)
2. Array operations must preserve order!
3. `random` should _replace_ existing field?
4. String operations should ignore non-string values?

Number 3. (and maybe 4.) should probably be part of the current pull request; the others can come independently.

/cc @fsteeg

**Comment by blackwinter** [comment] 2022-01-21 09:15
So what's the verdict? How do we proceed here?

**Comment by TobiasNx** [comment] 2022-01-21 09:21
Okay, I thought you already set the next steps. But perhaps should I test again with the new handling of preset arrays?

**Comment by blackwinter** [comment] 2022-01-21 09:30
> Okay, I thought you already set the next steps.

On which I didn't get any feedback...

We can ignore the hash order issue for now, I guess. But what about the string conversion issue? Should I address it?

> But perhaps should I test again with the new handling of preset arrays?

I would think so, yes.

**Comment by TobiasNx** [comment] 2022-01-21 11:08
I think the string conversation of non string values should be addressed yes.
Is this branch already handling the arrays or should I wait until it is merged and we keep this ticket open?

**Comment by blackwinter** [comment] 2022-01-21 11:41
> I think the string conversation of non string values should be addressed yes.

Fixed by 4cee91e. The remaining problem is that `append`/`prepend`/etc. also operate on arrays directly which they shouldn't (see disabled tests).

> Is this branch already handling the arrays

Yes, all discussed changes are included in the associated pull request.

**Comment by blackwinter** [comment] 2022-01-21 13:23
> The remaining problem is that `append`/`prepend`/etc. also operate on arrays directly which they shouldn't (see disabled tests).

Fixed by d802933.

**Comment by blackwinter** [comment] 2022-01-21 16:40
> `rename`: This only works on fields in an objects, not deeper nested structures.

Fixed by 1eebaac.

**Comment by TobiasNx** [comment] 2022-01-24 07:47
`random` still seems to have some troubles with arrays

**Comment by TobiasNx** [comment] 2022-01-24 08:32
`reverse` does not work with `*` in arrays.

**Comment by TobiasNx** [comment] 2022-01-24 08:33
`rename` i am not sure anymore if with `rename`: the sublevels should be change too as default or if that should be an option or done by the `each`-bind.

**Comment by blackwinter** [comment] 2022-01-24 10:04
> `random` still seems to have some troubles with arrays

These are expected (see #110; requires `set_array(...)`).

**Comment by TobiasNx** [comment] 2022-01-24 10:08
> > `random` still seems to have some troubles with arrays
> 
> These are expected (see #110; requires `set_array(...)`).

you are right, i didn't think about that.

**Comment by blackwinter** [comment] 2022-01-24 10:08
> `sort_field`: All options do not work yet.

See [comment above](https://github.com/metafacture/metafacture-fix/issues/100#issuecomment-1016346752) (use `"true"`).

> `sort_field`: Selecting arrays with * does not work

I'll have to investigate.

**Comment by blackwinter** [comment] 2022-01-24 10:12
In general, for inserting/transforming values with wildcards, see #102.

**Comment by blackwinter** [comment] 2022-01-24 10:18
> `reverse("animals[]")`: These seem not to work perhapse due to (JSON-)Array. Either way does not work.

Result shows `["zebra", "cat", "dog"]`, which is the reverse of `["dog", "cat", "zebra"]`. See also my [previous comment](https://github.com/metafacture/metafacture-fix/issues/100#issuecomment-1016346752).

**Comment by blackwinter** [comment] 2022-01-24 10:20
> `rename` i am not sure anymore if with `rename`: the sublevels should be change too as default or if that should be an option or done by the `each`-bind.

Catmandu [does it](https://github.com/hbz/Catmandu/blob/bb54964bb2afe6a4ad46ceeafb5b77a3023f28cb/t/Catmandu-Fix-rename.t#L15-L17) by default (can't be controlled by an option).

**Comment by blackwinter** [comment] 2022-01-25 15:41
> `split_field`: This results in empty array:

Without `move_field(...)` I get the indexed hash:

```json
"OTHERS" : [ {
  "tools" : {
    "1" : "hammer",
    "2" : "saw",
    "3" : "bow"
  }
} ]
```

So I would ascribe this to our array handling, not the `split_field` function itself.

Can you confirm?

**Comment by TobiasNx** [comment] 2022-01-26 08:48
Yes that is true and I can confirm that.

I have set up a separate test for moving arrays in object-arrays:

https://github.com/TobiasNx/fix-FunctionalReview-Testing/tree/master/data/testing/move_field_in_object_array

The problem seems to be something if you have an array in an object of an array and if you move this.

**Comment by TobiasNx** [comment] 2022-01-26 09:11
All in all, as discussed off board the function seem to work. All problems that are open are not related to the functions themselves:

1) Order of elements are changed.
2) Problems with index-wildcard in paths.

**Closed** 2022-01-26 10:12 UTC
