### ISSUE TITLE
copy_field/move_field to existing field does not overwrite but create an object

### ISSUE THREAD

**Issue by TobiasNx** [metafacture/metafacture-fix#99] opened 2021-12-22 09:26 UTC
When using `copy_field`/`move_field` to an existing field.
Fix does not overwrite but create an object with multiple instances. I would have expected that the field would be overwritten.

[See here](https://metafacture.org/playground/?data=%7B%0A++++%22animal%22%3A+%22dog%22%2C%0A++++%22bnimal%22%3A+%22cat%22%0A%7D&flux=PG_DATA%0A%7C+as-records%0A%7C+decode-json%0A%7C+fix%0A%7C+encode-json%28prettyPrinting%3D%22true%22%29%0A%7C+print%0A%3B&fix=copy_field%28%22bnimal%22%2C+%22animal%22%29&active-editor=fix)

Output is:
```
{
  "animal" : {
    "1" : "dog",
    "2" : "cat"
  },
  "bnimal" : "cat"
}
```

Output expected:
```
{
  "animal" : "cat",
  "bnimal" : "cat"
}
```

**Comment by TobiasNx** [comment] 2022-02-01 15:40
Perhaps this should also be true for add_field

**Comment by fsteeg** [comment] 2022-02-03 15:07
Duplicate of #116, closing.

**Closed by fsteeg** 2022-02-03 15:07 UTC
Labels: bug, duplicate
